import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const packageJsonPath = path.join(rootDir, 'package.json');
const swJsPath = path.join(rootDir, 'public', 'sw.js');
const versionTsPath = path.join(rootDir, 'src', 'version.ts');
const versionJsonPath = path.join(rootDir, 'public', 'version.json');

// 1. Read package.json
const pkg = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const currentVersion = pkg.version || '2.0.0';

// 2. Parse SemVer and increment patch
const parts = currentVersion.split('.').map((p) => parseInt(p, 10) || 0);
while (parts.length < 3) {
    parts.push(0);
}
// Increment patch version
parts[2] += 1;
const newVersion = parts.join('.');
const buildTimestamp = new Date().toISOString();

// 3. Update package.json
pkg.version = newVersion;
fs.writeFileSync(packageJsonPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8');

// 4. Update public/sw.js cache names
if (fs.existsSync(swJsPath)) {
    let swContent = fs.readFileSync(swJsPath, 'utf8');
    swContent = swContent.replace(
        /const CACHE_NAME = ['"]chopaeng-v[^'"]+['"];/,
        `const CACHE_NAME = 'chopaeng-v${newVersion}';`
    );
    swContent = swContent.replace(
        /const CATALOG_CACHE = ['"]chopaeng-catalog-v[^'"]+['"];/,
        `const CATALOG_CACHE = 'chopaeng-catalog-v${newVersion}';`
    );
    fs.writeFileSync(swJsPath, swContent, 'utf8');
}

// 5. Generate src/version.ts
const versionTsContent = `// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '${newVersion}';
export const BUILD_TIMESTAMP = '${buildTimestamp}';
export const APP_NAME = 'ChoPaeng';
`;
fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');

// 6. Generate public/version.json
const versionJsonContent = JSON.stringify(
    {
        version: newVersion,
        buildTimestamp,
        name: 'ChoPaeng',
    },
    null,
    2
);
fs.writeFileSync(versionJsonPath, versionJsonContent + '\n', 'utf8');

// Console feedback
console.log(`\x1b[32m✔ ChoPaeng Version Bumped:\x1b[0m \x1b[36mv${currentVersion}\x1b[0m ➔ \x1b[33m\x1b[1mv${newVersion}\x1b[0m \x1b[90m(${buildTimestamp})\x1b[0m`);
console.log(`\x1b[90m  • Updated package.json (${newVersion})\x1b[0m`);
console.log(`\x1b[90m  • Updated public/sw.js (chopaeng-v${newVersion})\x1b[0m`);
console.log(`\x1b[90m  • Generated src/version.ts\x1b[0m`);
console.log(`\x1b[90m  • Generated public/version.json\x1b[0m\n`);
