// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '2.0.1';
export const BUILD_TIMESTAMP = '2026-08-30T03:12:29.517Z';
export const APP_NAME = 'ChoPaeng';
