// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '2.0.38';
export const BUILD_TIMESTAMP = '2026-09-04T18:18:09.142Z';
export const APP_NAME = 'ChoPaeng';
