// Auto-generated by scripts/bump-version.mjs during build. Do not edit manually.
export const APP_VERSION = '2.0.23';
export const BUILD_TIMESTAMP = '2026-09-02T12:27:30.790Z';
export const APP_NAME = 'ChoPaeng';
